env:
  - SWIFT_VERSION=5.0
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - set -o pipefail
        - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme BricBrac | xcpretty -c
        - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme Curio | xcpretty -c
        - xcodebuild test -project BricBrac.xcodeproj -scheme BricBrac -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" | xcpretty -c
        - swift test
          #- os: linux
          #language: generic
          #sudo: required
          #dist: trusty
          #install:
          #- wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
          #- wget https://swift.org/builds/swift-${SWIFT_VERSION}-release/ubuntu1404/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz
          #- tar xzf swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz
          #- export PATH=${PWD}/swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
          #script:
          #- swift test

