name: BricBrac CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:    
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  macOS:
    runs-on: macos-latest
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  macOS11:
    runs-on: macos-11.0
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  Release:
    runs-on: ubuntu-latest
    needs: [Linux, macOS, macOS11]

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CHANGELOG.md
            RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

