name: BricBrac CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:    
  Linux:
    name: BricBrac Linux Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  macOS:
    name: BricBrac macOS Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  macOS11:
    name: BricBrac macOS11 Tests
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  Release:
    name: Release BricBrac
    runs-on: ubuntu-latest
    workflow_run:
      workflows:
        - 'BricBrac Linux Tests'
        - 'BricBrac macOS Tests'
        - 'BricBrac macOS11 Tests'
      types:
        - completed

    steps:
      - name: Release Snapshot
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          automatic_release_tag: "latest"
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release Tag
        if: startsWith(github.ref, 'refs/tags/') == true
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"

