name: Universal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 10:30AM & 10:30PM UTC
    - cron:  '30 10,22 * * *'

jobs:
  ci:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Test macOS
        run: swift test
      - name: Test Android
        uses: skiptools/swift-android-action@v1
      - name: Test iOS
        run: xcodebuild test -scheme "universal-Package" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 15"
      - name: Test watchOS
        run: xcodebuild test -scheme "universal-Package" -destination "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)"
      - name: Test tvOS
        run: xcodebuild test -scheme "universal-Package" -sdk "appletvsimulator" -destination "platform=tvOS Simulator,name=Apple TV" 

