name: BricBrac CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:    
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  macOS:
    runs-on: macos-latest
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  macOS11:
    runs-on: macos-11.0
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  Pre-Release:
    runs-on: ubuntu-latest
    needs: [Linux, macOS]

    steps:
      - name: Pre-Release Snapshot
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          automatic_release_tag: "latest"
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          # needed to override tag
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' 

  Release:
    runs-on: ubuntu-latest
    needs: [Linux, macOS]

    steps:
      - name: Release Tag
        if: startsWith(github.ref, 'refs/tags/') == true
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"

